[default]
#FastAPI
fastapi_title = "Dummy Repository Service"
fastapi_description = "This service mimics the B2SHARE Signposting module and an LDN Inbox module. It also publishes a '/status' enpoint, were the status of the archival request can be checked."
service_name = "dummy-repository-service"

resources_path = "@format {env[BASE_DIR]}/resources/linkset"

log_file = "@format {env[BASE_DIR]}/logs/drs.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"

db_driver = "sqlite3"
#data_db_file = "@format {env[BASE_DIR]}/data/db/dans_inbox.db"
data_db_file = "@format {env[BASE_DIR]}/data/db/dummy_inbox.db"